services:
  neo4j:
    image: neo4j:5
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/supersecret123   # >= 8 chars
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: supersecret123          # <-- match above
      IMAGE_ROOT: /data/images
      UPLOAD_ROOT: /data/uploads
      PAGE_SIZE: ${PAGE_SIZE:-20}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - "C:\\Users\\T.Abdellahi\\.cache\\huggingface:/root/.cache/huggingface"
      - ./images:/data/images
      - ./backend/uploads:/data/uploads
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://backend:8000}

volumes:
  neo4j_data:
