
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}         # Default root username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}      # Default root password
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}    # Ensure this matches Mongo root username
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}  # Ensure this matches Mongo root password
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/              # MongoDB URL with proper credentials
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}           # Optional, Mongo Express login
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin}           # Optional, Mongo Express login
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"


  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      MONGO_DB: ${MONGO_DB:-labeldb}
      MONGO_COLLECTION: ${MONGO_COLLECTION:-labels}
      IMAGE_ROOT: /data/images
      PAGE_SIZE: ${PAGE_SIZE:-20}
      BACKEND_PORT: ${BACKEND_PORT:-8000}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./images:/data/images:ro
      - ./backend:/app:ro         # <— add this line

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://backend:8000}  # Use the backend service name


volumes:
  mongo_data:
